---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack
  namespace: ${NAMESPACE}
  labels:
    app: snack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snack
  minReadySeconds: 10
  revisionHistoryLimit: 10
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 5
  template:
    metadata:
      labels:
        app: snack
    spec:
      restartPolicy: Always
      containers:
        - name: snack
          image: "${IMAGE}"
          env:
            - name: SNACK_PORT
              value: "3011"
            - name: SNACK_SERVER_HOST
              value: "${ENV_SUBDOMAIN_PREFIX}snack.expo.io"
            - name: IMPORT_SERVER_URL
              value: "${ENV_SUBDOMAIN_PREFIX}snackager.expo.io"
            - name: SNACK_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: snack-config
                  key: sentry-dsn
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: snack-config
                  key: sentry-environment
          ports:
          - containerPort: 80
            name: http
          readinessProbe:
            httpGet:
              path: "/"
              port: 3011
            initialDelaySeconds: 1
          livenessProbe:
            httpGet:
              path: "/"
              port: 3011
            initialDelaySeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 200m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: snack
  namespace: ${NAMESPACE}
  labels:
    app: snack
spec:
  selector:
    app: snack
  ports:
  - name: http
    port: 80
    targetPort: 3011
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: snack
  namespace: ${NAMESPACE}
  labels:
    app: snack
    ssl: "true"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - ${ENV_SUBDOMAIN_PREFIX}snack.expo.io
    secretName: snack-tls
  rules:
    - host: ${ENV_SUBDOMAIN_PREFIX}snack.expo.io
      http:
        paths:
        - backend:
            serviceName: snack
            servicePort: 80
          path: /
